# Generated by Django 4.0.2 on 2022-02-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='hi', max_length=300),
            preserve_default=False,
        ),
    ]
